  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka

  okta:
  Aauth2:
  issuer:https://dev-15585796.okta.com/oauth2/default
  audiance: api://default


