server:
  port: 9296

spring:
  application:
    name: CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raghabsingh99/Microservices-implementation-.git
          clone-on-start: true
          # Optionally specify the branch
          # branch: main

  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
