server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raghabsingh99/Microservices-implementation-.git
          clone-on-start: true
          default-label: master
          # Optionally specify the branch
          # branch: main

  server:
    port: 8761

  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
    instance:
      hostname: http://localhost:8761/eureka

